version: '3.3'

networks:
  webnetwork:
    driver: bridge

services:
  prometheus:
    hostname: prometheus
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-admin-api"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    links:
      - node-exporter
    networks:
      - webnetwork
  node-exporter:
    hostname: node-exporter
    image: bitnami/node-exporter
    ports:
      - "9100:9100"
    networks:
      - webnetwork

